<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Job;

class JobSeeder extends Seeder
{
    public function run(): void
    {
        $jobs = [
            [
                'title' => 'Laravel Developer',
                'company' => 'TechNova Pvt. Ltd.',
                'location' => 'Remote',
                'salary' => '₹12,000 - ₹18,000 a month',
                'type' => 'Full-time',
                'shift' => 'Day Shift',
                'skills' => 'CodeIgniter, MongoDB, HTML5, CSS3, OOP PHP',
                'company_logo' => 'assets/company_logos/logo1.png',
                'cover_image' => 'assets/cover_images/cover1.jpg',
                'recruiter_id' => null,
                'description' => 'Develop and maintain Laravel applications.',
                'requirements' => '2+ years experience with Laravel, MySQL, REST APIs.',
                'responsibilities' => 'Write clean code, collaborate with team, deliver on time.',
                'benefits' => 'Remote work, Health insurance, Flexible hours.',
                'application_url' => null,
                'deadline' => now()->addDays(30)->toDateString(),
                'is_remote' => true,
                'employment_level' => 'Mid',
                'industry' => 'IT Services',
                'experience' => '2+ years',
                'education' => 'B.Tech/B.E. in Computer Science',
            ],
            [
                'title' => 'Frontend Developer',
                'company' => 'Creative Minds',
                'location' => 'Bangalore, India',
                'salary' => '₹18,000 - ₹25,000 a month',
                'type' => 'Full-time',
                'shift' => 'Night Shift',
                'skills' => 'ReactJS, JavaScript, Tailwind CSS',
                'company_logo' => null,
                'cover_image' => 'assets/cover_images/cover1.jpg',
                'recruiter_id' => null,
                'description' => 'Design and build modern web interfaces using ReactJS and Tailwind CSS.',
                'requirements' => '1+ year experience with ReactJS, JavaScript, and CSS frameworks.',
                'responsibilities' => 'Develop UI components, collaborate with backend, ensure responsive design.',
                'benefits' => 'Flexible hours, Remote option, Team outings.',
                'application_url' => null,
                'deadline' => now()->addDays(25)->toDateString(),
                'is_remote' => false,
                'employment_level' => 'Entry',
                'industry' => 'Software Development',
                'experience' => '1+ year',
                'education' => 'Any Graduate',
            ],
            [
                'title' => 'Backend Engineer',
                'company' => 'CodeSphere',
                'location' => 'Delhi NCR, India',
                'salary' => '₹20,000 - ₹30,000 a month',
                'type' => 'Full-time',
                'shift' => 'Flexible',
                'skills' => 'Node.js, Express, MongoDB, REST API',
                'company_logo' => 'assets/company_logos/logo1.png',
                'cover_image' => null,
                'recruiter_id' => null,
                'description' => 'Build and maintain scalable backend services.',
                'requirements' => '2+ years Node.js, MongoDB, RESTful APIs.',
                'responsibilities' => 'API development, database design, code reviews.',
                'benefits' => 'Health insurance, Learning budget.',
                'application_url' => null,
                'deadline' => now()->addDays(20)->toDateString(),
                'is_remote' => false,
                'employment_level' => 'Mid',
                'industry' => 'IT',
                'experience' => '2+ years',
                'education' => 'B.Sc/B.Tech',
            ],
            [
                'title' => 'Mobile App Developer',
                'company' => 'Appify Solutions',
                'location' => 'Hyderabad, India',
                'salary' => '₹25,000 - ₹35,000 a month',
                'type' => 'Full-time',
                'shift' => 'Day Shift',
                'skills' => 'Flutter, Dart, Firebase',
                'company_logo' => null,
                'cover_image' => null,
                'recruiter_id' => null,
                'description' => 'Develop cross-platform mobile apps using Flutter.',
                'requirements' => 'Experience with Flutter and Firebase.',
                'responsibilities' => 'App development, bug fixing, publishing to stores.',
                'benefits' => 'Flexible work, Annual bonus.',
                'application_url' => null,
                'deadline' => now()->addDays(18)->toDateString(),
                'is_remote' => false,
                'employment_level' => 'Mid',
                'industry' => 'Mobile',
                'experience' => '1+ year',
                'education' => 'Any Graduate',
            ],
            [
                'title' => 'UI/UX Designer',
                'company' => 'DesignHaus',
                'location' => 'Remote',
                'salary' => '₹18,000 - ₹22,000 a month',
                'type' => 'Contract',
                'shift' => 'Flexible',
                'skills' => 'Figma, Adobe XD, UI Kits, Wireframing',
                'company_logo' => 'assets/company_logos/logo1.png',
                'cover_image' => 'assets/cover_images/cover1.jpg',
                'recruiter_id' => null,
                'description' => 'Create intuitive and engaging user interfaces and experiences.',
                'requirements' => 'Proficiency in design tools like Figma, Adobe XD.',
                'responsibilities' => 'Design user flows, wireframes, prototypes, and high-fidelity mockups.',
                'benefits' => 'Work from anywhere, Flexible schedule, Creative freedom.',
                'application_url' => null,
                'deadline' => null,
                'is_remote' => true,
                'employment_level' => null,
                'industry' => null,
                'experience' => null,
                'education' => null,
            ],
            [
                'title' => 'Software Tester',
                'company' => 'QATech',
                'location' => 'Kolkata, India',
                'salary' => '₹15,000 - ₹20,000 a month',
                'type' => 'Full-time',
                'shift' => 'Day Shift',
                'skills' => 'Manual Testing, Selenium, JIRA',
                'company_logo' => null,
                'cover_image' => 'assets/cover_images/cover1.jpg',
                'recruiter_id' => null,
                'description' => 'Ensure software quality through manual and automated testing.',
                'requirements' => 'Experience with Selenium, JIRA, and manual testing.',
                'responsibilities' => 'Design test cases, execute tests, report bugs, and verify fixes.',
                'benefits' => 'Health benefits, Paid time off, Work from home options.',
                'application_url' => null,
                'deadline' => null,
                'is_remote' => false,
                'employment_level' => null,
                'industry' => null,
                'experience' => null,
                'education' => null,
            ],
            [
                'title' => 'Python Developer',
                'company' => 'AI Logic',
                'location' => 'Chennai, India',
                'salary' => '₹22,000 - ₹28,000 a month',
                'type' => 'Full-time',
                'shift' => 'Morning Shift',
                'skills' => 'Python, Django, REST Framework, PostgreSQL',
                'company_logo' => 'assets/company_logos/logo1.png',
                'cover_image' => null,
                'recruiter_id' => null,
                'description' => 'Develop server-side web application logic using Python and Django.',
                'requirements' => '2+ years of experience in Python, Django, and RESTful APIs.',
                'responsibilities' => 'Develop backend components, connect applications with other web services, and assist front-end developers.',
                'benefits' => 'Remote work, Flexible hours, Health insurance.',
                'application_url' => null,
                'deadline' => null,
                'is_remote' => false,
                'employment_level' => null,
                'industry' => null,
                'experience' => null,
                'education' => null,
            ],
            [
                'title' => 'DevOps Engineer',
                'company' => 'CloudCore',
                'location' => 'Remote',
                'salary' => '₹30,000 - ₹45,000 a month',
                'type' => 'Full-time',
                'shift' => 'Flexible',
                'skills' => 'Docker, Kubernetes, AWS, CI/CD',
                'company_logo' => null,
                'cover_image' => null,
                'recruiter_id' => null,
                'description' => 'Manage and optimize cloud infrastructure and CI/CD pipelines.',
                'requirements' => '3+ years of experience in DevOps, AWS, Docker, and Kubernetes.',
                'responsibilities' => 'Implement and manage CI/CD pipelines, monitor system performance, and troubleshoot issues.',
                'benefits' => 'Work from home, Flexible schedule, Professional development opportunities.',
                'application_url' => null,
                'deadline' => null,
                'is_remote' => true,
                'employment_level' => null,
                'industry' => null,
                'experience' => null,
                'education' => null,
            ],
            [
                'title' => 'WordPress Developer',
                'company' => 'WP Builders',
                'location' => 'Jaipur, India',
                'salary' => '₹15,000 - ₹20,000 a month',
                'type' => 'Part-time',
                'shift' => 'Day Shift',
                'skills' => 'PHP, WordPress, Elementor, WooCommerce',
                'company_logo' => 'assets/company_logos/logo1.png',
                'cover_image' => 'assets/cover_images/cover1.jpg',
                'recruiter_id' => null,
                'description' => 'Create and manage WordPress websites and plugins.',
                'requirements' => 'Proficiency in PHP, WordPress, and MySQL.',
                'responsibilities' => 'Develop WordPress plugins, customize themes, and optimize websites for performance.',
                'benefits' => 'Flexible hours, Remote work, Project-based bonuses.',
                'application_url' => null,
                'deadline' => null,
                'is_remote' => false,
                'employment_level' => null,
                'industry' => null,
                'experience' => null,
                'education' => null,
            ],
            [
                'title' => 'React Native Developer',
                'company' => 'Mobitech',
                'location' => 'Pune, India',
                'salary' => '₹20,000 - ₹30,000 a month',
                'type' => 'Full-time',
                'shift' => 'Day Shift',
                'skills' => 'React Native, Redux, API Integration',
                'company_logo' => null,
                'cover_image' => 'assets/cover_images/cover1.jpg',
                'recruiter_id' => null,
                'description' => 'Build mobile applications using React Native and integrate with backend services.',
                'requirements' => '1+ year experience in mobile app development with React Native.',
                'responsibilities' => 'Develop mobile app features, optimize app performance, and ensure quality user experience.',
                'benefits' => 'Work from home, Flexible hours, Health insurance.',
                'application_url' => null,
                'deadline' => null,
                'is_remote' => false,
                'employment_level' => null,
                'industry' => null,
                'experience' => null,
                'education' => null,
            ],
            [
                'title' => 'QA Engineer',
                'company' => 'Testify',
                'location' => 'Ahmedabad, India',
                'salary' => '₹16,000 - ₹22,000 a month',
                'type' => 'Full-time',
                'shift' => 'Day Shift',
                'skills' => 'Testing, Automation, Bug Tracking',
                'company_logo' => null,
                'cover_image' => null,
                'recruiter_id' => null,
                'description' => 'Ensure the quality and functionality of software applications through rigorous testing.',
                'requirements' => 'Experience in software testing, automation tools, and bug tracking systems.',
                'responsibilities' => 'Design and execute test plans, identify and report bugs, and verify fixes.',
                'benefits' => 'Health benefits, Paid time off, Work from home options.',
                'application_url' => null,
                'deadline' => null,
                'is_remote' => false,
                'employment_level' => null,
                'industry' => null,
                'experience' => null,
                'education' => null,
            ],
            [
                'title' => 'Full Stack Developer',
                'company' => 'StackUp',
                'location' => 'Remote',
                'salary' => '₹28,000 - ₹40,000 a month',
                'type' => 'Full-time',
                'shift' => 'Flexible',
                'skills' => 'PHP, Vue.js, MySQL, AWS',
                'company_logo' => 'assets/company_logos/logo1.png',
                'cover_image' => null,
                'recruiter_id' => null,
                'description' => 'Develop complete web applications, from front-end to back-end.',
                'requirements' => '3+ years of experience in full-stack development, PHP, and MySQL.',
                'responsibilities' => 'Develop and maintain web applications, ensure high performance, and collaborate with other developers.',
                'benefits' => 'Remote work, Flexible hours, Health insurance.',
                'application_url' => null,
                'deadline' => null,
                'is_remote' => true,
                'employment_level' => null,
                'industry' => null,
                'experience' => null,
                'education' => null,
            ],
            [
                'title' => 'Support Engineer',
                'company' => 'HelpDesk',
                'location' => 'Delhi, India',
                'salary' => '₹14,000 - ₹18,000 a month',
                'type' => 'Full-time',
                'shift' => 'Night Shift',
                'skills' => 'Support, Customer Service',
                'company_logo' => null,
                'cover_image' => null,
                'recruiter_id' => null,
                'description' => 'Provide technical support and assistance to customers.',
                'requirements' => 'Excellent communication skills and basic technical knowledge.',
                'responsibilities' => 'Respond to customer inquiries, troubleshoot issues, and provide solutions.',
                'benefits' => 'Night shift allowance, Health insurance, Paid time off.',
                'application_url' => null,
                'deadline' => null,
                'is_remote' => false,
                'employment_level' => null,
                'industry' => null,
                'experience' => null,
                'education' => null,
            ],
            [
                'title' => 'Business Analyst',
                'company' => 'BizTech',
                'location' => 'Mumbai, India',
                'salary' => '₹25,000 - ₹32,000 a month',
                'type' => 'Contract',
                'shift' => 'Day Shift',
                'skills' => 'Analysis, Excel, Reporting',
                'company_logo' => null,
                'cover_image' => 'assets/cover_images/cover1.jpg',
                'recruiter_id' => null,
                'description' => 'Analyze business requirements and provide data-driven insights.',
                'requirements' => 'Proficiency in Excel and experience in data analysis.',
                'responsibilities' => 'Gather and analyze data, prepare reports, and present findings to stakeholders.',
                'benefits' => 'Contract completion bonus, Flexible hours, Remote work option.',
                'application_url' => null,
                'deadline' => null,
                'is_remote' => false,
                'employment_level' => null,
                'industry' => null,
                'experience' => null,
                'education' => null,
            ],
            [
                'title' => 'Cloud Architect',
                'company' => 'Cloudify',
                'location' => 'Remote',
                'salary' => '₹40,000 - ₹60,000 a month',
                'type' => 'Full-time',
                'shift' => 'Flexible',
                'skills' => 'AWS, Azure, GCP',
                'company_logo' => 'assets/company_logos/logo1.png',
                'cover_image' => null,
                'recruiter_id' => null,
                'description' => 'Design and manage cloud architecture solutions.',
                'requirements' => '5+ years of experience in cloud computing and architecture design.',
                'responsibilities' => 'Design cloud solutions, manage cloud resources, and ensure security and compliance.',
                'benefits' => 'Work from home, Flexible schedule, Professional development opportunities.',
                'application_url' => null,
                'deadline' => null,
                'is_remote' => true,
                'employment_level' => null,
                'industry' => null,
                'experience' => null,
                'education' => null,
            ],
            [
                'title' => 'Network Engineer',
                'company' => 'NetSecure',
                'location' => 'Chandigarh, India',
                'salary' => '₹18,000 - ₹25,000 a month',
                'type' => 'Full-time',
                'shift' => 'Day Shift',
                'skills' => 'Networking, Security, Linux',
                'company_logo' => null,
                'cover_image' => null,
                'recruiter_id' => null,
                'description' => 'Manage and maintain network infrastructure and security.',
                'requirements' => '2+ years of experience in network administration and security.',
                'responsibilities' => 'Monitor network performance, troubleshoot issues, and implement security measures.',
                'benefits' => 'Health insurance, Paid time off, Work from home options.',
                'application_url' => null,
                'deadline' => null,
                'is_remote' => false,
                'employment_level' => null,
                'industry' => null,
                'experience' => null,
                'education' => null,
            ],
            [
                'title' => 'Mobile Tester',
                'company' => 'AppTesters',
                'location' => 'Bangalore, India',
                'salary' => '₹13,000 - ₹17,000 a month',
                'type' => 'Full-time',
                'shift' => 'Day Shift',
                'skills' => 'Android, iOS, Testing',
                'company_logo' => null,
                'cover_image' => null,
                'recruiter_id' => null,
                'description' => 'Test mobile applications on Android and iOS platforms.',
                'requirements' => 'Experience in mobile app testing and familiarity with testing tools.',
                'responsibilities' => 'Execute test cases, report bugs, and verify fixes on mobile applications.',
                'benefits' => 'Health benefits, Paid time off, Work from home options.',
                'application_url' => null,
                'deadline' => null,
                'is_remote' => false,
                'employment_level' => null,
                'industry' => null,
                'experience' => null,
                'education' => null,
            ],
            [
                'title' => 'Backend PHP Developer',
                'company' => 'WebWorks',
                'location' => 'Pune, India',
                'salary' => '₹20,000 - ₹28,000 a month',
                'type' => 'Full-time',
                'shift' => 'Day Shift',
                'skills' => 'PHP, Laravel, MySQL',
                'company_logo' => 'assets/company_logos/logo1.png',
                'cover_image' => null,
                'recruiter_id' => null,
                'description' => 'Develop server-side applications and APIs using PHP and Laravel.',
                'requirements' => '2+ years of experience in PHP, Laravel, and MySQL.',
                'responsibilities' => 'Develop and maintain APIs, manage database operations, and ensure application security.',
                'benefits' => 'Health insurance, Paid time off, Work from home options.',
                'application_url' => null,
                'deadline' => null,
                'is_remote' => false,
                'employment_level' => null,
                'industry' => null,
                'experience' => null,
                'education' => null,
            ],
            [
                'title' => 'Angular Developer',
                'company' => 'Frontify',
                'location' => 'Hyderabad, India',
                'salary' => '₹22,000 - ₹30,000 a month',
                'type' => 'Full-time',
                'shift' => 'Day Shift',
                'skills' => 'Angular, TypeScript, RxJS',
                'company_logo' => null,
                'cover_image' => 'assets/cover_images/cover1.jpg',
                'recruiter_id' => null,
                'description' => 'Develop dynamic web applications using Angular and TypeScript.',
                'requirements' => '1+ year experience in Angular, TypeScript, and RxJS.',
                'responsibilities' => 'Develop application components, integrate with backend services, and ensure high performance.',
                'benefits' => 'Flexible hours, Remote work, Health insurance.',
                'application_url' => null,
                'deadline' => null,
                'is_remote' => false,
                'employment_level' => null,
                'industry' => null,
                'experience' => null,
                'education' => null,
            ],
            [
                'title' => 'SEO Specialist',
                'company' => 'RankUp',
                'location' => 'Remote',
                'salary' => '₹15,000 - ₹22,000 a month',
                'type' => 'Contract',
                'shift' => 'Flexible',
                'skills' => 'SEO, Google Analytics, Content',
                'company_logo' => null,
                'cover_image' => null,
                'recruiter_id' => null,
                'description' => 'Optimize website content and structure for search engines.',
                'requirements' => 'Experience with SEO tools and Google Analytics.',
                'responsibilities' => 'Conduct keyword research, on-page optimization, and performance analysis.',
                'benefits' => 'Work from anywhere, Flexible schedule, Performance bonuses.',
                'application_url' => null,
                'deadline' => null,
                'is_remote' => true,
                'employment_level' => null,
                'industry' => null,
                'experience' => null,
                'education' => null,
            ],
        ];

        foreach ($jobs as $job) {
            Job::create($job);
        }
    }
}
